name: torch_bricks
channels:
  - pytorch
  - nvidia
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10.*  # or don't specify the version and use the latest stable Python
  - pytorch::pytorch=2.0.1  # Only real package requirement
  - torchmetrics=0.11.4     # Only real package requirement
  - mamba
  - conda-lock
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - pytorch::torchvision=0.15.2
  - pytorch::pytorch-cuda=11.7
  - pytorch-lightning=2.0.2
  - hydra-core=1.3.2
  # Linting stuff
  - pre-commit=3.3.2
  - coverage=7.2.5
  - pytest=7.3.1
  - pytest-cov=4.0.0

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
