# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests_linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: torch_bricks
          environment-file: conda-linux-64.lock
          cache-environment: true
          generate-run-shell: true
      - name: Run linter
        run: make lint
        shell: micromamba-shell {0}
      - name: Run tests
        run: make test
        shell: micromamba-shell {0}
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
